// ignore_for_file: avoid_print

library;

import 'dart:io';
import 'package:ffigen/ffigen.dart';

/// Generates `lib/src/third_party/assimp_c.g.dart` — `@Native` bindings to the
/// C bridge (`src/assimp_bridge.h`), resolved through the native-assets hook
/// (`hook/build.dart` names the library asset after this file).
///
/// Usage: `dart run tool/ffigen.dart`
void main() {
  final packageRoot = Platform.script.resolve('../');
  FfiGenerator(
    headers: Headers(
      entryPoints: [packageRoot.resolve('src/assimp_bridge.h')],
      include: (header) => header.path.endsWith('assimp_bridge.h'),
    ),
    functions: Functions(include: Declarations.includeAll),
    enums: Enums(include: Declarations.includeAll),
    output: Output(
      dartFile: packageRoot.resolve('lib/src/third_party/assimp_c.g.dart'),
      format: true,
      preamble: '''
// AUTO-GENERATED FILE — DO NOT MODIFY.
// Generated by package:ffigen via tool/ffigen.dart.
// To regenerate: dart run tool/ffigen.dart

// ignore_for_file: type=lint, unused_import, unused_element
// ignore_for_file: camel_case_types, non_constant_identifier_names
// ignore_for_file: constant_identifier_names
''',
    ),
  ).generate();
  print('Generated lib/src/third_party/assimp_c.g.dart');
}
