name: flutter_riglogic_example
description: "Demonstrates how to use the flutter_riglogic package."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.0
  flutter: ">=3.0.0"
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_riglogic:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sample.dna
