// ignore_for_file: avoid_print

/// Regenerates lib/src/bindings/flutter_kimodo_bindings.g.dart from
/// src/flutter_kimodo.h (and the vendored src/kimodo/kimodo_capi.h it
/// includes). Needs libclang (LLVM); `test/bindings_lockstep_test.dart`
/// checks the result against the headers.
///
///   dart run tool/ffigen.dart
library;

import 'dart:io';

import 'package:ffigen/ffigen.dart';

void main() {
  final root = Platform.script.resolve('../');
  FfiGenerator(
    headers: Headers(
      entryPoints: [root.resolve('src/flutter_kimodo.h')],
      include: (header) =>
          header.path.endsWith('flutter_kimodo.h') ||
          header.path.endsWith('kimodo_capi.h'),
      compilerOptions: ['-I${root.resolve('src').toFilePath()}'],
    ),
    // Only the wrapper's functions: the kimodo_* functions live in
    // kimodo.dll, which flutter_kimodo loads itself.
    functions: Functions(
      include: (declaration) =>
          declaration.originalName.startsWith('flutter_kimodo_'),
    ),
    enums: Enums(include: Declarations.includeAll),
    structs: Structs(include: Declarations.includeAll),
    macros: Macros(
      include: (declaration) =>
          declaration.originalName == 'KIMODO_CAPI_ABI_VERSION',
    ),
    output: Output(
      dartFile: root.resolve('lib/src/bindings/flutter_kimodo_bindings.g.dart'),
      format: true,
      preamble: '''
// AUTO-GENERATED by tool/ffigen.dart from src/flutter_kimodo.h — do not edit.

// ignore_for_file: type=lint, unused_import, unused_element
// ignore_for_file: camel_case_types, non_constant_identifier_names
// ignore_for_file: constant_identifier_names
''',
    ),
  ).generate();
  print('generated lib/src/bindings/flutter_kimodo_bindings.g.dart');
}
