// ignore_for_file: avoid_print

library;

import 'dart:io';

import 'package:ffigen/ffigen.dart';

/// Generates `lib/src/bindings/gstreamer.g.dart`: dynamic-library bindings
/// (a `GStreamerBindings` class built from a symbol lookup, no link-time
/// dependency) for the GStreamer core, app and pbutils API this package uses,
/// plus the GLib / GObject helpers they need.
///
/// Usage (from `flutter_gstreamer/`):
///
///     dart run tool/ffigen.dart
///
/// Needs:
///  * the GStreamer development headers: `GSTREAMER_INCLUDE_ROOT` (a folder
///    holding `gstreamer-1.0/`, `glib-2.0/`), else `<root>/include` of the
///    GStreamer install found through `GSTREAMER_1_0_ROOT_MSVC_X86_64` /
///    `GSTREAMER_1_0_ROOT_X86_64` / the per-user Windows install, else
///    `/usr/include` (Linux, `libgstreamer1.0-dev` +
///    `libgstreamer-plugins-base1.0-dev`). `GLIBCONFIG_INCLUDE` overrides the
///    folder holding `glibconfig.h` (Linux: `/usr/lib/x86_64-linux-gnu/glib-2.0/include`).
///  * libclang: `LIBCLANG_PATH` (the `libclang.dll` / `.so` / `.dylib` file),
///    else ffigen's default LLVM lookup. Without an LLVM install,
///    `pip install --target <dir> libclang` ships a usable
///    `<dir>/clang/native/libclang.dll`.
///
/// The bindings only use fixed-size or ABI-specific (`Long`, `Size`) types,
/// so the file generated from the Windows headers is valid on 64-bit Linux
/// and macOS too.
void main() {
  final packageRoot = Platform.script.resolve('../');
  final include = _includeRoot();
  final glibconfig =
      Platform.environment['GLIBCONFIG_INCLUDE'] ??
      (Directory('$include/../lib/glib-2.0/include').existsSync()
          ? '$include/../lib/glib-2.0/include'
          : '/usr/lib/x86_64-linux-gnu/glib-2.0/include');
  final libclang = Platform.environment['LIBCLANG_PATH'];
  print('GStreamer headers: $include');

  FfiGenerator(
    headers: Headers(
      entryPoints: [packageRoot.resolve('tool/gstreamer_ffigen.h')],
      compilerOptions: [
        '-I$include/gstreamer-1.0',
        '-I$include/glib-2.0',
        '-I$glibconfig',
        '-I$include',
        // Declare gst_message_unref & co. as plain exported functions
        // instead of static inlines.
        '-DGST_DISABLE_MINIOBJECT_INLINE_FUNCTIONS',
      ],
    ),
    functions: Functions.includeSet(_functions),
    structs: Structs(
      include: Declarations.includeSet(_structs),
      // `struct _GstBuffer` → `GstBuffer` (a leading `_` would make it private).
      rename: (d) => d.originalName.startsWith('_')
          ? d.originalName.substring(1)
          : d.originalName,
    ),
    enums: Enums(
      include: Declarations.includeSet(_enums),
      // Several are bit masks (GstMessageType) or get compared with plain
      // ints coming back from C, so int constants rather than Dart enums.
      style: (_, _) => EnumStyle.intConstants,
      // All of these are plain `int`-sized C enums on every supported ABI.
      silenceWarning: true,
    ),
    unions: Unions(
      include: Declarations.includeSet({'GMutex', '_GMutex'}),
      rename: (d) => d.originalName.startsWith('_')
          ? d.originalName.substring(1)
          : d.originalName,
    ),
    typedefs: Typedefs.includeSet({'GstClockTime', 'GType'}),
    output: Output(
      dartFile: packageRoot.resolve('lib/src/bindings/gstreamer.g.dart'),
      style: const DynamicLibraryBindings(
        wrapperName: 'GStreamerBindings',
        wrapperDocComment:
            'Raw GStreamer 1.x / GLib bindings. Build with '
            '`GStreamerBindings.fromLookup` over the loaded GStreamer libraries '
            '(see `GStreamerLibraries`).',
      ),
      format: true,
      sort: true,
      preamble: '''
// AUTO-GENERATED FILE — DO NOT MODIFY.
// Generated by package:ffigen via tool/ffigen.dart from the GStreamer 1.x
// headers (LGPL-2.1+; this file only declares their C API).
// To regenerate: dart run tool/ffigen.dart

// ignore_for_file: type=lint, unused_import, unused_element
// ignore_for_file: camel_case_types, non_constant_identifier_names
// ignore_for_file: constant_identifier_names
''',
    ),
  ).generate(libclangDylib: libclang == null ? null : Uri.file(libclang));
  print('Generated lib/src/bindings/gstreamer.g.dart');
}

String _includeRoot() {
  final env = Platform.environment;
  final explicit = env['GSTREAMER_INCLUDE_ROOT'];
  if (explicit != null) return explicit.replaceAll('\\', '/');
  final roots = [
    env['GSTREAMER_1_0_ROOT_MSVC_X86_64'],
    env['GSTREAMER_1_0_ROOT_X86_64'],
    if (env['LOCALAPPDATA'] != null)
      '${env['LOCALAPPDATA']}/Programs/gstreamer/1.0/msvc_x86_64',
    'C:/Program Files/gstreamer/1.0/msvc_x86_64',
    'C:/gstreamer/1.0/msvc_x86_64',
    '/Library/Frameworks/GStreamer.framework/Versions/1.0',
  ];
  for (final root in roots.whereType<String>()) {
    final include = '${root.replaceAll('\\', '/')}/include';
    if (Directory('$include/gstreamer-1.0').existsSync()) return include;
  }
  return '/usr/include';
}

/// Every C function the bindings expose.
const _functions = {
  // GLib / GObject
  'g_free',
  'g_error_free',
  'g_setenv',
  'g_getenv',
  'g_list_length',
  'g_list_nth_data',
  'g_object_ref',
  'g_object_unref',
  // Init / version
  'gst_init_check',
  'gst_is_initialized',
  'gst_version',
  'gst_version_string',
  'gst_filename_to_uri',
  'gst_util_set_object_arg',
  // Registry
  'gst_registry_get',
  'gst_registry_find_plugin',
  'gst_element_factory_find',
  'gst_element_factory_make',
  // Objects, elements, pipelines
  'gst_object_ref',
  'gst_object_unref',
  'gst_object_get_name',
  'gst_parse_launch',
  'gst_pipeline_new',
  'gst_bin_get_by_name',
  'gst_element_set_state',
  'gst_element_get_state',
  'gst_element_get_bus',
  'gst_element_send_event',
  'gst_element_query_duration',
  'gst_element_query_position',
  'gst_element_get_static_pad',
  'gst_element_state_get_name',
  'gst_event_new_eos',
  'gst_pad_get_current_caps',
  // Bus & messages
  'gst_bus_timed_pop_filtered',
  'gst_message_parse_error',
  'gst_message_parse_warning',
  'gst_message_type_get_name',
  'gst_message_unref',
  // Mini objects, buffers, samples, caps, structures
  'gst_mini_object_ref',
  'gst_mini_object_unref',
  'gst_buffer_new_allocate',
  'gst_buffer_fill',
  'gst_buffer_get_size',
  'gst_buffer_extract',
  'gst_buffer_map',
  'gst_buffer_unmap',
  'gst_sample_get_buffer',
  'gst_sample_get_caps',
  'gst_caps_from_string',
  'gst_caps_to_string',
  'gst_caps_get_size',
  'gst_caps_get_structure',
  'gst_caps_unref',
  'gst_structure_get_name',
  'gst_structure_get_int',
  'gst_structure_get_fraction',
  // App library
  'gst_app_src_push_buffer',
  'gst_app_src_end_of_stream',
  'gst_app_src_set_caps',
  'gst_app_sink_try_pull_sample',
  'gst_app_sink_is_eos',
  // pbutils: GstDiscoverer
  'gst_pb_utils_init',
  'gst_discoverer_new',
  'gst_discoverer_discover_uri',
  'gst_discoverer_info_get_result',
  'gst_discoverer_info_get_duration',
  'gst_discoverer_info_get_seekable',
  'gst_discoverer_info_get_stream_info',
  'gst_discoverer_info_get_video_streams',
  'gst_discoverer_info_get_audio_streams',
  'gst_discoverer_stream_info_get_caps',
  'gst_discoverer_stream_info_get_stream_type_nick',
  'gst_discoverer_stream_info_list_free',
  'gst_discoverer_video_info_get_width',
  'gst_discoverer_video_info_get_height',
  'gst_discoverer_video_info_get_framerate_num',
  'gst_discoverer_video_info_get_framerate_denom',
  'gst_discoverer_video_info_get_bitrate',
};

/// Structs generated with their fields (the rest are opaque).
final _structs = <String>{
  for (final name in [
    'GError',
    'GList',
    'GstMiniObject',
    'GstBuffer',
    'GstMessage',
    'GstMapInfo',
  ]) ...[name, '_$name'],
};

const _enums = {
  'GstState',
  'GstStateChangeReturn',
  'GstMessageType',
  'GstFlowReturn',
  'GstFormat',
  'GstMapFlags',
  'GstDiscovererResult',
};
