// AUTO-GENERATED FILE — DO NOT MODIFY.
// Generated by package:ffigen via tool/ffigen.dart from the GStreamer 1.x
// headers (LGPL-2.1+; this file only declares their C API).
// To regenerate: dart run tool/ffigen.dart

// ignore_for_file: type=lint, unused_import, unused_element
// ignore_for_file: camel_case_types, non_constant_identifier_names
// ignore_for_file: constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: unused_import
import 'dart:ffi' as ffi;

/// Raw GStreamer 1.x / GLib bindings. Build with `GStreamerBindings.fromLookup` over the loaded GStreamer libraries (see `GStreamerLibraries`).
class GStreamerBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  GStreamerBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  GStreamerBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  void g_error_free(ffi.Pointer<GError> error) {
    return _g_error_free(error);
  }

  late final _g_error_freePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GError>)>>(
        'g_error_free',
      );
  late final _g_error_free = _g_error_freePtr
      .asFunction<void Function(ffi.Pointer<GError>)>();

  void g_free(ffi.Pointer<ffi.Void> mem) {
    return _g_free(mem);
  }

  late final _g_freePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'g_free',
      );
  late final _g_free = _g_freePtr
      .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  ffi.Pointer<ffi.Char> g_getenv(ffi.Pointer<ffi.Char> variable) {
    return _g_getenv(variable);
  }

  late final _g_getenvPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)
        >
      >('g_getenv');
  late final _g_getenv = _g_getenvPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)>();

  int g_list_length(ffi.Pointer<GList> list) {
    return _g_list_length(list);
  }

  late final _g_list_lengthPtr =
      _lookup<ffi.NativeFunction<ffi.UnsignedInt Function(ffi.Pointer<GList>)>>(
        'g_list_length',
      );
  late final _g_list_length = _g_list_lengthPtr
      .asFunction<int Function(ffi.Pointer<GList>)>();

  ffi.Pointer<ffi.Void> g_list_nth_data(ffi.Pointer<GList> list, int n) {
    return _g_list_nth_data(list, n);
  }

  late final _g_list_nth_dataPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Void> Function(ffi.Pointer<GList>, ffi.UnsignedInt)
        >
      >('g_list_nth_data');
  late final _g_list_nth_data = _g_list_nth_dataPtr
      .asFunction<ffi.Pointer<ffi.Void> Function(ffi.Pointer<GList>, int)>();

  ffi.Pointer<ffi.Void> g_object_ref(ffi.Pointer<ffi.Void> object) {
    return _g_object_ref(object);
  }

  late final _g_object_refPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)
        >
      >('g_object_ref');
  late final _g_object_ref = _g_object_refPtr
      .asFunction<ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)>();

  void g_object_unref(ffi.Pointer<ffi.Void> object) {
    return _g_object_unref(object);
  }

  late final _g_object_unrefPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'g_object_unref',
      );
  late final _g_object_unref = _g_object_unrefPtr
      .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  int g_setenv(
    ffi.Pointer<ffi.Char> variable,
    ffi.Pointer<ffi.Char> value,
    int overwrite,
  ) {
    return _g_setenv(variable, value, overwrite);
  }

  late final _g_setenvPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Int,
          )
        >
      >('g_setenv');
  late final _g_setenv = _g_setenvPtr
      .asFunction<
        int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, int)
      >();

  int gst_app_sink_is_eos(ffi.Pointer<GstAppSink> appsink) {
    return _gst_app_sink_is_eos(appsink);
  }

  late final _gst_app_sink_is_eosPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<GstAppSink>)>>(
        'gst_app_sink_is_eos',
      );
  late final _gst_app_sink_is_eos = _gst_app_sink_is_eosPtr
      .asFunction<int Function(ffi.Pointer<GstAppSink>)>();

  ffi.Pointer<GstSample> gst_app_sink_try_pull_sample(
    ffi.Pointer<GstAppSink> appsink,
    int timeout,
  ) {
    return _gst_app_sink_try_pull_sample(appsink, timeout);
  }

  late final _gst_app_sink_try_pull_samplePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<GstSample> Function(ffi.Pointer<GstAppSink>, GstClockTime)
        >
      >('gst_app_sink_try_pull_sample');
  late final _gst_app_sink_try_pull_sample = _gst_app_sink_try_pull_samplePtr
      .asFunction<
        ffi.Pointer<GstSample> Function(ffi.Pointer<GstAppSink>, int)
      >();

  int gst_app_src_end_of_stream(ffi.Pointer<GstAppSrc> appsrc) {
    return _gst_app_src_end_of_stream(appsrc);
  }

  late final _gst_app_src_end_of_streamPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<GstAppSrc>)>>(
        'gst_app_src_end_of_stream',
      );
  late final _gst_app_src_end_of_stream = _gst_app_src_end_of_streamPtr
      .asFunction<int Function(ffi.Pointer<GstAppSrc>)>();

  int gst_app_src_push_buffer(
    ffi.Pointer<GstAppSrc> appsrc,
    ffi.Pointer<GstBuffer> buffer,
  ) {
    return _gst_app_src_push_buffer(appsrc, buffer);
  }

  late final _gst_app_src_push_bufferPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<GstAppSrc>, ffi.Pointer<GstBuffer>)
        >
      >('gst_app_src_push_buffer');
  late final _gst_app_src_push_buffer = _gst_app_src_push_bufferPtr
      .asFunction<
        int Function(ffi.Pointer<GstAppSrc>, ffi.Pointer<GstBuffer>)
      >();

  void gst_app_src_set_caps(
    ffi.Pointer<GstAppSrc> appsrc,
    ffi.Pointer<GstCaps> caps,
  ) {
    return _gst_app_src_set_caps(appsrc, caps);
  }

  late final _gst_app_src_set_capsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<GstAppSrc>, ffi.Pointer<GstCaps>)
        >
      >('gst_app_src_set_caps');
  late final _gst_app_src_set_caps = _gst_app_src_set_capsPtr
      .asFunction<
        void Function(ffi.Pointer<GstAppSrc>, ffi.Pointer<GstCaps>)
      >();

  ffi.Pointer<GstElement> gst_bin_get_by_name(
    ffi.Pointer<GstBin> bin,
    ffi.Pointer<ffi.Char> name,
  ) {
    return _gst_bin_get_by_name(bin, name);
  }

  late final _gst_bin_get_by_namePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<GstElement> Function(
            ffi.Pointer<GstBin>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('gst_bin_get_by_name');
  late final _gst_bin_get_by_name = _gst_bin_get_by_namePtr
      .asFunction<
        ffi.Pointer<GstElement> Function(
          ffi.Pointer<GstBin>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  int gst_buffer_extract(
    ffi.Pointer<GstBuffer> buffer,
    int offset,
    ffi.Pointer<ffi.Void> dest,
    int size,
  ) {
    return _gst_buffer_extract(buffer, offset, dest, size);
  }

  late final _gst_buffer_extractPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.UnsignedLongLong Function(
            ffi.Pointer<GstBuffer>,
            ffi.UnsignedLongLong,
            ffi.Pointer<ffi.Void>,
            ffi.UnsignedLongLong,
          )
        >
      >('gst_buffer_extract');
  late final _gst_buffer_extract = _gst_buffer_extractPtr
      .asFunction<
        int Function(ffi.Pointer<GstBuffer>, int, ffi.Pointer<ffi.Void>, int)
      >();

  int gst_buffer_fill(
    ffi.Pointer<GstBuffer> buffer,
    int offset,
    ffi.Pointer<ffi.Void> src,
    int size,
  ) {
    return _gst_buffer_fill(buffer, offset, src, size);
  }

  late final _gst_buffer_fillPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.UnsignedLongLong Function(
            ffi.Pointer<GstBuffer>,
            ffi.UnsignedLongLong,
            ffi.Pointer<ffi.Void>,
            ffi.UnsignedLongLong,
          )
        >
      >('gst_buffer_fill');
  late final _gst_buffer_fill = _gst_buffer_fillPtr
      .asFunction<
        int Function(ffi.Pointer<GstBuffer>, int, ffi.Pointer<ffi.Void>, int)
      >();

  int gst_buffer_get_size(ffi.Pointer<GstBuffer> buffer) {
    return _gst_buffer_get_size(buffer);
  }

  late final _gst_buffer_get_sizePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.UnsignedLongLong Function(ffi.Pointer<GstBuffer>)
        >
      >('gst_buffer_get_size');
  late final _gst_buffer_get_size = _gst_buffer_get_sizePtr
      .asFunction<int Function(ffi.Pointer<GstBuffer>)>();

  int gst_buffer_map(
    ffi.Pointer<GstBuffer> buffer,
    ffi.Pointer<GstMapInfo> info,
    int flags,
  ) {
    return _gst_buffer_map(buffer, info, flags);
  }

  late final _gst_buffer_mapPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<GstBuffer>,
            ffi.Pointer<GstMapInfo>,
            ffi.UnsignedInt,
          )
        >
      >('gst_buffer_map');
  late final _gst_buffer_map = _gst_buffer_mapPtr
      .asFunction<
        int Function(ffi.Pointer<GstBuffer>, ffi.Pointer<GstMapInfo>, int)
      >();

  ffi.Pointer<GstBuffer> gst_buffer_new_allocate(
    ffi.Pointer<GstAllocator> allocator,
    int size,
    ffi.Pointer<GstAllocationParams> params,
  ) {
    return _gst_buffer_new_allocate(allocator, size, params);
  }

  late final _gst_buffer_new_allocatePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<GstBuffer> Function(
            ffi.Pointer<GstAllocator>,
            ffi.UnsignedLongLong,
            ffi.Pointer<GstAllocationParams>,
          )
        >
      >('gst_buffer_new_allocate');
  late final _gst_buffer_new_allocate = _gst_buffer_new_allocatePtr
      .asFunction<
        ffi.Pointer<GstBuffer> Function(
          ffi.Pointer<GstAllocator>,
          int,
          ffi.Pointer<GstAllocationParams>,
        )
      >();

  void gst_buffer_unmap(
    ffi.Pointer<GstBuffer> buffer,
    ffi.Pointer<GstMapInfo> info,
  ) {
    return _gst_buffer_unmap(buffer, info);
  }

  late final _gst_buffer_unmapPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<GstBuffer>, ffi.Pointer<GstMapInfo>)
        >
      >('gst_buffer_unmap');
  late final _gst_buffer_unmap = _gst_buffer_unmapPtr
      .asFunction<
        void Function(ffi.Pointer<GstBuffer>, ffi.Pointer<GstMapInfo>)
      >();

  ffi.Pointer<GstMessage> gst_bus_timed_pop_filtered(
    ffi.Pointer<GstBus> bus,
    int timeout,
    int types,
  ) {
    return _gst_bus_timed_pop_filtered(bus, timeout, types);
  }

  late final _gst_bus_timed_pop_filteredPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<GstMessage> Function(
            ffi.Pointer<GstBus>,
            GstClockTime,
            ffi.Int,
          )
        >
      >('gst_bus_timed_pop_filtered');
  late final _gst_bus_timed_pop_filtered = _gst_bus_timed_pop_filteredPtr
      .asFunction<
        ffi.Pointer<GstMessage> Function(ffi.Pointer<GstBus>, int, int)
      >();

  ffi.Pointer<GstCaps> gst_caps_from_string(ffi.Pointer<ffi.Char> string) {
    return _gst_caps_from_string(string);
  }

  late final _gst_caps_from_stringPtr =
      _lookup<
        ffi.NativeFunction<ffi.Pointer<GstCaps> Function(ffi.Pointer<ffi.Char>)>
      >('gst_caps_from_string');
  late final _gst_caps_from_string = _gst_caps_from_stringPtr
      .asFunction<ffi.Pointer<GstCaps> Function(ffi.Pointer<ffi.Char>)>();

  int gst_caps_get_size(ffi.Pointer<GstCaps> caps) {
    return _gst_caps_get_size(caps);
  }

  late final _gst_caps_get_sizePtr =
      _lookup<
        ffi.NativeFunction<ffi.UnsignedInt Function(ffi.Pointer<GstCaps>)>
      >('gst_caps_get_size');
  late final _gst_caps_get_size = _gst_caps_get_sizePtr
      .asFunction<int Function(ffi.Pointer<GstCaps>)>();

  ffi.Pointer<GstStructure> gst_caps_get_structure(
    ffi.Pointer<GstCaps> caps,
    int index,
  ) {
    return _gst_caps_get_structure(caps, index);
  }

  late final _gst_caps_get_structurePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<GstStructure> Function(
            ffi.Pointer<GstCaps>,
            ffi.UnsignedInt,
          )
        >
      >('gst_caps_get_structure');
  late final _gst_caps_get_structure = _gst_caps_get_structurePtr
      .asFunction<
        ffi.Pointer<GstStructure> Function(ffi.Pointer<GstCaps>, int)
      >();

  ffi.Pointer<ffi.Char> gst_caps_to_string(ffi.Pointer<GstCaps> caps) {
    return _gst_caps_to_string(caps);
  }

  late final _gst_caps_to_stringPtr =
      _lookup<
        ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<GstCaps>)>
      >('gst_caps_to_string');
  late final _gst_caps_to_string = _gst_caps_to_stringPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<GstCaps>)>();

  void gst_caps_unref(ffi.Pointer<GstCaps> caps) {
    return _gst_caps_unref(caps);
  }

  late final _gst_caps_unrefPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GstCaps>)>>(
        'gst_caps_unref',
      );
  late final _gst_caps_unref = _gst_caps_unrefPtr
      .asFunction<void Function(ffi.Pointer<GstCaps>)>();

  ffi.Pointer<GstDiscovererInfo> gst_discoverer_discover_uri(
    ffi.Pointer<GstDiscoverer> discoverer,
    ffi.Pointer<ffi.Char> uri,
    ffi.Pointer<ffi.Pointer<GError>> err,
  ) {
    return _gst_discoverer_discover_uri(discoverer, uri, err);
  }

  late final _gst_discoverer_discover_uriPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<GstDiscovererInfo> Function(
            ffi.Pointer<GstDiscoverer>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<GError>>,
          )
        >
      >('gst_discoverer_discover_uri');
  late final _gst_discoverer_discover_uri = _gst_discoverer_discover_uriPtr
      .asFunction<
        ffi.Pointer<GstDiscovererInfo> Function(
          ffi.Pointer<GstDiscoverer>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Pointer<GError>>,
        )
      >();

  ffi.Pointer<GList> gst_discoverer_info_get_audio_streams(
    ffi.Pointer<GstDiscovererInfo> info,
  ) {
    return _gst_discoverer_info_get_audio_streams(info);
  }

  late final _gst_discoverer_info_get_audio_streamsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<GList> Function(ffi.Pointer<GstDiscovererInfo>)
        >
      >('gst_discoverer_info_get_audio_streams');
  late final _gst_discoverer_info_get_audio_streams =
      _gst_discoverer_info_get_audio_streamsPtr
          .asFunction<
            ffi.Pointer<GList> Function(ffi.Pointer<GstDiscovererInfo>)
          >();

  int gst_discoverer_info_get_duration(ffi.Pointer<GstDiscovererInfo> info) {
    return _gst_discoverer_info_get_duration(info);
  }

  late final _gst_discoverer_info_get_durationPtr =
      _lookup<
        ffi.NativeFunction<
          GstClockTime Function(ffi.Pointer<GstDiscovererInfo>)
        >
      >('gst_discoverer_info_get_duration');
  late final _gst_discoverer_info_get_duration =
      _gst_discoverer_info_get_durationPtr
          .asFunction<int Function(ffi.Pointer<GstDiscovererInfo>)>();

  int gst_discoverer_info_get_result(ffi.Pointer<GstDiscovererInfo> info) {
    return _gst_discoverer_info_get_result(info);
  }

  late final _gst_discoverer_info_get_resultPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.UnsignedInt Function(ffi.Pointer<GstDiscovererInfo>)
        >
      >('gst_discoverer_info_get_result');
  late final _gst_discoverer_info_get_result =
      _gst_discoverer_info_get_resultPtr
          .asFunction<int Function(ffi.Pointer<GstDiscovererInfo>)>();

  int gst_discoverer_info_get_seekable(ffi.Pointer<GstDiscovererInfo> info) {
    return _gst_discoverer_info_get_seekable(info);
  }

  late final _gst_discoverer_info_get_seekablePtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Pointer<GstDiscovererInfo>)>
      >('gst_discoverer_info_get_seekable');
  late final _gst_discoverer_info_get_seekable =
      _gst_discoverer_info_get_seekablePtr
          .asFunction<int Function(ffi.Pointer<GstDiscovererInfo>)>();

  ffi.Pointer<GstDiscovererStreamInfo> gst_discoverer_info_get_stream_info(
    ffi.Pointer<GstDiscovererInfo> info,
  ) {
    return _gst_discoverer_info_get_stream_info(info);
  }

  late final _gst_discoverer_info_get_stream_infoPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<GstDiscovererStreamInfo> Function(
            ffi.Pointer<GstDiscovererInfo>,
          )
        >
      >('gst_discoverer_info_get_stream_info');
  late final _gst_discoverer_info_get_stream_info =
      _gst_discoverer_info_get_stream_infoPtr
          .asFunction<
            ffi.Pointer<GstDiscovererStreamInfo> Function(
              ffi.Pointer<GstDiscovererInfo>,
            )
          >();

  ffi.Pointer<GList> gst_discoverer_info_get_video_streams(
    ffi.Pointer<GstDiscovererInfo> info,
  ) {
    return _gst_discoverer_info_get_video_streams(info);
  }

  late final _gst_discoverer_info_get_video_streamsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<GList> Function(ffi.Pointer<GstDiscovererInfo>)
        >
      >('gst_discoverer_info_get_video_streams');
  late final _gst_discoverer_info_get_video_streams =
      _gst_discoverer_info_get_video_streamsPtr
          .asFunction<
            ffi.Pointer<GList> Function(ffi.Pointer<GstDiscovererInfo>)
          >();

  ffi.Pointer<GstDiscoverer> gst_discoverer_new(
    int timeout,
    ffi.Pointer<ffi.Pointer<GError>> err,
  ) {
    return _gst_discoverer_new(timeout, err);
  }

  late final _gst_discoverer_newPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<GstDiscoverer> Function(
            GstClockTime,
            ffi.Pointer<ffi.Pointer<GError>>,
          )
        >
      >('gst_discoverer_new');
  late final _gst_discoverer_new = _gst_discoverer_newPtr
      .asFunction<
        ffi.Pointer<GstDiscoverer> Function(
          int,
          ffi.Pointer<ffi.Pointer<GError>>,
        )
      >();

  ffi.Pointer<GstCaps> gst_discoverer_stream_info_get_caps(
    ffi.Pointer<GstDiscovererStreamInfo> info,
  ) {
    return _gst_discoverer_stream_info_get_caps(info);
  }

  late final _gst_discoverer_stream_info_get_capsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<GstCaps> Function(ffi.Pointer<GstDiscovererStreamInfo>)
        >
      >('gst_discoverer_stream_info_get_caps');
  late final _gst_discoverer_stream_info_get_caps =
      _gst_discoverer_stream_info_get_capsPtr
          .asFunction<
            ffi.Pointer<GstCaps> Function(ffi.Pointer<GstDiscovererStreamInfo>)
          >();

  ffi.Pointer<ffi.Char> gst_discoverer_stream_info_get_stream_type_nick(
    ffi.Pointer<GstDiscovererStreamInfo> info,
  ) {
    return _gst_discoverer_stream_info_get_stream_type_nick(info);
  }

  late final _gst_discoverer_stream_info_get_stream_type_nickPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<GstDiscovererStreamInfo>)
        >
      >('gst_discoverer_stream_info_get_stream_type_nick');
  late final _gst_discoverer_stream_info_get_stream_type_nick =
      _gst_discoverer_stream_info_get_stream_type_nickPtr
          .asFunction<
            ffi.Pointer<ffi.Char> Function(ffi.Pointer<GstDiscovererStreamInfo>)
          >();

  void gst_discoverer_stream_info_list_free(ffi.Pointer<GList> infos) {
    return _gst_discoverer_stream_info_list_free(infos);
  }

  late final _gst_discoverer_stream_info_list_freePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GList>)>>(
        'gst_discoverer_stream_info_list_free',
      );
  late final _gst_discoverer_stream_info_list_free =
      _gst_discoverer_stream_info_list_freePtr
          .asFunction<void Function(ffi.Pointer<GList>)>();

  int gst_discoverer_video_info_get_bitrate(
    ffi.Pointer<GstDiscovererVideoInfo> info,
  ) {
    return _gst_discoverer_video_info_get_bitrate(info);
  }

  late final _gst_discoverer_video_info_get_bitratePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.UnsignedInt Function(ffi.Pointer<GstDiscovererVideoInfo>)
        >
      >('gst_discoverer_video_info_get_bitrate');
  late final _gst_discoverer_video_info_get_bitrate =
      _gst_discoverer_video_info_get_bitratePtr
          .asFunction<int Function(ffi.Pointer<GstDiscovererVideoInfo>)>();

  int gst_discoverer_video_info_get_framerate_denom(
    ffi.Pointer<GstDiscovererVideoInfo> info,
  ) {
    return _gst_discoverer_video_info_get_framerate_denom(info);
  }

  late final _gst_discoverer_video_info_get_framerate_denomPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.UnsignedInt Function(ffi.Pointer<GstDiscovererVideoInfo>)
        >
      >('gst_discoverer_video_info_get_framerate_denom');
  late final _gst_discoverer_video_info_get_framerate_denom =
      _gst_discoverer_video_info_get_framerate_denomPtr
          .asFunction<int Function(ffi.Pointer<GstDiscovererVideoInfo>)>();

  int gst_discoverer_video_info_get_framerate_num(
    ffi.Pointer<GstDiscovererVideoInfo> info,
  ) {
    return _gst_discoverer_video_info_get_framerate_num(info);
  }

  late final _gst_discoverer_video_info_get_framerate_numPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.UnsignedInt Function(ffi.Pointer<GstDiscovererVideoInfo>)
        >
      >('gst_discoverer_video_info_get_framerate_num');
  late final _gst_discoverer_video_info_get_framerate_num =
      _gst_discoverer_video_info_get_framerate_numPtr
          .asFunction<int Function(ffi.Pointer<GstDiscovererVideoInfo>)>();

  int gst_discoverer_video_info_get_height(
    ffi.Pointer<GstDiscovererVideoInfo> info,
  ) {
    return _gst_discoverer_video_info_get_height(info);
  }

  late final _gst_discoverer_video_info_get_heightPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.UnsignedInt Function(ffi.Pointer<GstDiscovererVideoInfo>)
        >
      >('gst_discoverer_video_info_get_height');
  late final _gst_discoverer_video_info_get_height =
      _gst_discoverer_video_info_get_heightPtr
          .asFunction<int Function(ffi.Pointer<GstDiscovererVideoInfo>)>();

  int gst_discoverer_video_info_get_width(
    ffi.Pointer<GstDiscovererVideoInfo> info,
  ) {
    return _gst_discoverer_video_info_get_width(info);
  }

  late final _gst_discoverer_video_info_get_widthPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.UnsignedInt Function(ffi.Pointer<GstDiscovererVideoInfo>)
        >
      >('gst_discoverer_video_info_get_width');
  late final _gst_discoverer_video_info_get_width =
      _gst_discoverer_video_info_get_widthPtr
          .asFunction<int Function(ffi.Pointer<GstDiscovererVideoInfo>)>();

  ffi.Pointer<GstElementFactory> gst_element_factory_find(
    ffi.Pointer<ffi.Char> name,
  ) {
    return _gst_element_factory_find(name);
  }

  late final _gst_element_factory_findPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<GstElementFactory> Function(ffi.Pointer<ffi.Char>)
        >
      >('gst_element_factory_find');
  late final _gst_element_factory_find = _gst_element_factory_findPtr
      .asFunction<
        ffi.Pointer<GstElementFactory> Function(ffi.Pointer<ffi.Char>)
      >();

  ffi.Pointer<GstElement> gst_element_factory_make(
    ffi.Pointer<ffi.Char> factoryname,
    ffi.Pointer<ffi.Char> name,
  ) {
    return _gst_element_factory_make(factoryname, name);
  }

  late final _gst_element_factory_makePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<GstElement> Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('gst_element_factory_make');
  late final _gst_element_factory_make = _gst_element_factory_makePtr
      .asFunction<
        ffi.Pointer<GstElement> Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  ffi.Pointer<GstBus> gst_element_get_bus(ffi.Pointer<GstElement> element) {
    return _gst_element_get_bus(element);
  }

  late final _gst_element_get_busPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<GstBus> Function(ffi.Pointer<GstElement>)
        >
      >('gst_element_get_bus');
  late final _gst_element_get_bus = _gst_element_get_busPtr
      .asFunction<ffi.Pointer<GstBus> Function(ffi.Pointer<GstElement>)>();

  int gst_element_get_state(
    ffi.Pointer<GstElement> element,
    ffi.Pointer<ffi.UnsignedInt> state,
    ffi.Pointer<ffi.UnsignedInt> pending,
    int timeout,
  ) {
    return _gst_element_get_state(element, state, pending, timeout);
  }

  late final _gst_element_get_statePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.UnsignedInt Function(
            ffi.Pointer<GstElement>,
            ffi.Pointer<ffi.UnsignedInt>,
            ffi.Pointer<ffi.UnsignedInt>,
            GstClockTime,
          )
        >
      >('gst_element_get_state');
  late final _gst_element_get_state = _gst_element_get_statePtr
      .asFunction<
        int Function(
          ffi.Pointer<GstElement>,
          ffi.Pointer<ffi.UnsignedInt>,
          ffi.Pointer<ffi.UnsignedInt>,
          int,
        )
      >();

  ffi.Pointer<GstPad> gst_element_get_static_pad(
    ffi.Pointer<GstElement> element,
    ffi.Pointer<ffi.Char> name,
  ) {
    return _gst_element_get_static_pad(element, name);
  }

  late final _gst_element_get_static_padPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<GstPad> Function(
            ffi.Pointer<GstElement>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('gst_element_get_static_pad');
  late final _gst_element_get_static_pad = _gst_element_get_static_padPtr
      .asFunction<
        ffi.Pointer<GstPad> Function(
          ffi.Pointer<GstElement>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  int gst_element_query_duration(
    ffi.Pointer<GstElement> element,
    int format,
    ffi.Pointer<ffi.LongLong> duration,
  ) {
    return _gst_element_query_duration(element, format, duration);
  }

  late final _gst_element_query_durationPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<GstElement>,
            ffi.UnsignedInt,
            ffi.Pointer<ffi.LongLong>,
          )
        >
      >('gst_element_query_duration');
  late final _gst_element_query_duration = _gst_element_query_durationPtr
      .asFunction<
        int Function(ffi.Pointer<GstElement>, int, ffi.Pointer<ffi.LongLong>)
      >();

  int gst_element_query_position(
    ffi.Pointer<GstElement> element,
    int format,
    ffi.Pointer<ffi.LongLong> cur,
  ) {
    return _gst_element_query_position(element, format, cur);
  }

  late final _gst_element_query_positionPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<GstElement>,
            ffi.UnsignedInt,
            ffi.Pointer<ffi.LongLong>,
          )
        >
      >('gst_element_query_position');
  late final _gst_element_query_position = _gst_element_query_positionPtr
      .asFunction<
        int Function(ffi.Pointer<GstElement>, int, ffi.Pointer<ffi.LongLong>)
      >();

  int gst_element_send_event(
    ffi.Pointer<GstElement> element,
    ffi.Pointer<GstEvent> event,
  ) {
    return _gst_element_send_event(element, event);
  }

  late final _gst_element_send_eventPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<GstElement>, ffi.Pointer<GstEvent>)
        >
      >('gst_element_send_event');
  late final _gst_element_send_event = _gst_element_send_eventPtr
      .asFunction<
        int Function(ffi.Pointer<GstElement>, ffi.Pointer<GstEvent>)
      >();

  int gst_element_set_state(ffi.Pointer<GstElement> element, int state) {
    return _gst_element_set_state(element, state);
  }

  late final _gst_element_set_statePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.UnsignedInt Function(ffi.Pointer<GstElement>, ffi.UnsignedInt)
        >
      >('gst_element_set_state');
  late final _gst_element_set_state = _gst_element_set_statePtr
      .asFunction<int Function(ffi.Pointer<GstElement>, int)>();

  ffi.Pointer<ffi.Char> gst_element_state_get_name(int state) {
    return _gst_element_state_get_name(state);
  }

  late final _gst_element_state_get_namePtr =
      _lookup<
        ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.UnsignedInt)>
      >('gst_element_state_get_name');
  late final _gst_element_state_get_name = _gst_element_state_get_namePtr
      .asFunction<ffi.Pointer<ffi.Char> Function(int)>();

  ffi.Pointer<GstEvent> gst_event_new_eos() {
    return _gst_event_new_eos();
  }

  late final _gst_event_new_eosPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<GstEvent> Function()>>(
        'gst_event_new_eos',
      );
  late final _gst_event_new_eos = _gst_event_new_eosPtr
      .asFunction<ffi.Pointer<GstEvent> Function()>();

  ffi.Pointer<ffi.Char> gst_filename_to_uri(
    ffi.Pointer<ffi.Char> filename,
    ffi.Pointer<ffi.Pointer<GError>> error,
  ) {
    return _gst_filename_to_uri(filename, error);
  }

  late final _gst_filename_to_uriPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<GError>>,
          )
        >
      >('gst_filename_to_uri');
  late final _gst_filename_to_uri = _gst_filename_to_uriPtr
      .asFunction<
        ffi.Pointer<ffi.Char> Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Pointer<GError>>,
        )
      >();

  int gst_init_check(
    ffi.Pointer<ffi.Int> argc,
    ffi.Pointer<ffi.Pointer<ffi.Pointer<ffi.Char>>> argv,
    ffi.Pointer<ffi.Pointer<GError>> error,
  ) {
    return _gst_init_check(argc, argv, error);
  }

  late final _gst_init_checkPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Int>,
            ffi.Pointer<ffi.Pointer<ffi.Pointer<ffi.Char>>>,
            ffi.Pointer<ffi.Pointer<GError>>,
          )
        >
      >('gst_init_check');
  late final _gst_init_check = _gst_init_checkPtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Int>,
          ffi.Pointer<ffi.Pointer<ffi.Pointer<ffi.Char>>>,
          ffi.Pointer<ffi.Pointer<GError>>,
        )
      >();

  int gst_is_initialized() {
    return _gst_is_initialized();
  }

  late final _gst_is_initializedPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>('gst_is_initialized');
  late final _gst_is_initialized = _gst_is_initializedPtr
      .asFunction<int Function()>();

  void gst_message_parse_error(
    ffi.Pointer<GstMessage> message,
    ffi.Pointer<ffi.Pointer<GError>> gerror,
    ffi.Pointer<ffi.Pointer<ffi.Char>> debug,
  ) {
    return _gst_message_parse_error(message, gerror, debug);
  }

  late final _gst_message_parse_errorPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<GstMessage>,
            ffi.Pointer<ffi.Pointer<GError>>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('gst_message_parse_error');
  late final _gst_message_parse_error = _gst_message_parse_errorPtr
      .asFunction<
        void Function(
          ffi.Pointer<GstMessage>,
          ffi.Pointer<ffi.Pointer<GError>>,
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
        )
      >();

  void gst_message_parse_warning(
    ffi.Pointer<GstMessage> message,
    ffi.Pointer<ffi.Pointer<GError>> gerror,
    ffi.Pointer<ffi.Pointer<ffi.Char>> debug,
  ) {
    return _gst_message_parse_warning(message, gerror, debug);
  }

  late final _gst_message_parse_warningPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<GstMessage>,
            ffi.Pointer<ffi.Pointer<GError>>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('gst_message_parse_warning');
  late final _gst_message_parse_warning = _gst_message_parse_warningPtr
      .asFunction<
        void Function(
          ffi.Pointer<GstMessage>,
          ffi.Pointer<ffi.Pointer<GError>>,
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
        )
      >();

  ffi.Pointer<ffi.Char> gst_message_type_get_name(int type) {
    return _gst_message_type_get_name(type);
  }

  late final _gst_message_type_get_namePtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.Int)>>(
        'gst_message_type_get_name',
      );
  late final _gst_message_type_get_name = _gst_message_type_get_namePtr
      .asFunction<ffi.Pointer<ffi.Char> Function(int)>();

  void gst_message_unref(ffi.Pointer<GstMessage> msg) {
    return _gst_message_unref(msg);
  }

  late final _gst_message_unrefPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GstMessage>)>>(
        'gst_message_unref',
      );
  late final _gst_message_unref = _gst_message_unrefPtr
      .asFunction<void Function(ffi.Pointer<GstMessage>)>();

  ffi.Pointer<GstMiniObject> gst_mini_object_ref(
    ffi.Pointer<GstMiniObject> mini_object,
  ) {
    return _gst_mini_object_ref(mini_object);
  }

  late final _gst_mini_object_refPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<GstMiniObject> Function(ffi.Pointer<GstMiniObject>)
        >
      >('gst_mini_object_ref');
  late final _gst_mini_object_ref = _gst_mini_object_refPtr
      .asFunction<
        ffi.Pointer<GstMiniObject> Function(ffi.Pointer<GstMiniObject>)
      >();

  void gst_mini_object_unref(ffi.Pointer<GstMiniObject> mini_object) {
    return _gst_mini_object_unref(mini_object);
  }

  late final _gst_mini_object_unrefPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GstMiniObject>)>
      >('gst_mini_object_unref');
  late final _gst_mini_object_unref = _gst_mini_object_unrefPtr
      .asFunction<void Function(ffi.Pointer<GstMiniObject>)>();

  ffi.Pointer<ffi.Char> gst_object_get_name(ffi.Pointer<GstObject> object) {
    return _gst_object_get_name(object);
  }

  late final _gst_object_get_namePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<GstObject>)
        >
      >('gst_object_get_name');
  late final _gst_object_get_name = _gst_object_get_namePtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<GstObject>)>();

  ffi.Pointer<ffi.Void> gst_object_ref(ffi.Pointer<ffi.Void> object) {
    return _gst_object_ref(object);
  }

  late final _gst_object_refPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)
        >
      >('gst_object_ref');
  late final _gst_object_ref = _gst_object_refPtr
      .asFunction<ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)>();

  void gst_object_unref(ffi.Pointer<ffi.Void> object) {
    return _gst_object_unref(object);
  }

  late final _gst_object_unrefPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'gst_object_unref',
      );
  late final _gst_object_unref = _gst_object_unrefPtr
      .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  ffi.Pointer<GstCaps> gst_pad_get_current_caps(ffi.Pointer<GstPad> pad) {
    return _gst_pad_get_current_caps(pad);
  }

  late final _gst_pad_get_current_capsPtr =
      _lookup<
        ffi.NativeFunction<ffi.Pointer<GstCaps> Function(ffi.Pointer<GstPad>)>
      >('gst_pad_get_current_caps');
  late final _gst_pad_get_current_caps = _gst_pad_get_current_capsPtr
      .asFunction<ffi.Pointer<GstCaps> Function(ffi.Pointer<GstPad>)>();

  ffi.Pointer<GstElement> gst_parse_launch(
    ffi.Pointer<ffi.Char> pipeline_description,
    ffi.Pointer<ffi.Pointer<GError>> error,
  ) {
    return _gst_parse_launch(pipeline_description, error);
  }

  late final _gst_parse_launchPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<GstElement> Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<GError>>,
          )
        >
      >('gst_parse_launch');
  late final _gst_parse_launch = _gst_parse_launchPtr
      .asFunction<
        ffi.Pointer<GstElement> Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Pointer<GError>>,
        )
      >();

  void gst_pb_utils_init() {
    return _gst_pb_utils_init();
  }

  late final _gst_pb_utils_initPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>('gst_pb_utils_init');
  late final _gst_pb_utils_init = _gst_pb_utils_initPtr
      .asFunction<void Function()>();

  ffi.Pointer<GstElement> gst_pipeline_new(ffi.Pointer<ffi.Char> name) {
    return _gst_pipeline_new(name);
  }

  late final _gst_pipeline_newPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<GstElement> Function(ffi.Pointer<ffi.Char>)
        >
      >('gst_pipeline_new');
  late final _gst_pipeline_new = _gst_pipeline_newPtr
      .asFunction<ffi.Pointer<GstElement> Function(ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<GstPlugin> gst_registry_find_plugin(
    ffi.Pointer<GstRegistry> registry,
    ffi.Pointer<ffi.Char> name,
  ) {
    return _gst_registry_find_plugin(registry, name);
  }

  late final _gst_registry_find_pluginPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<GstPlugin> Function(
            ffi.Pointer<GstRegistry>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('gst_registry_find_plugin');
  late final _gst_registry_find_plugin = _gst_registry_find_pluginPtr
      .asFunction<
        ffi.Pointer<GstPlugin> Function(
          ffi.Pointer<GstRegistry>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  ffi.Pointer<GstRegistry> gst_registry_get() {
    return _gst_registry_get();
  }

  late final _gst_registry_getPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<GstRegistry> Function()>>(
        'gst_registry_get',
      );
  late final _gst_registry_get = _gst_registry_getPtr
      .asFunction<ffi.Pointer<GstRegistry> Function()>();

  ffi.Pointer<GstBuffer> gst_sample_get_buffer(ffi.Pointer<GstSample> sample) {
    return _gst_sample_get_buffer(sample);
  }

  late final _gst_sample_get_bufferPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<GstBuffer> Function(ffi.Pointer<GstSample>)
        >
      >('gst_sample_get_buffer');
  late final _gst_sample_get_buffer = _gst_sample_get_bufferPtr
      .asFunction<ffi.Pointer<GstBuffer> Function(ffi.Pointer<GstSample>)>();

  ffi.Pointer<GstCaps> gst_sample_get_caps(ffi.Pointer<GstSample> sample) {
    return _gst_sample_get_caps(sample);
  }

  late final _gst_sample_get_capsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<GstCaps> Function(ffi.Pointer<GstSample>)
        >
      >('gst_sample_get_caps');
  late final _gst_sample_get_caps = _gst_sample_get_capsPtr
      .asFunction<ffi.Pointer<GstCaps> Function(ffi.Pointer<GstSample>)>();

  int gst_structure_get_fraction(
    ffi.Pointer<GstStructure> structure,
    ffi.Pointer<ffi.Char> fieldname,
    ffi.Pointer<ffi.Int> value_numerator,
    ffi.Pointer<ffi.Int> value_denominator,
  ) {
    return _gst_structure_get_fraction(
      structure,
      fieldname,
      value_numerator,
      value_denominator,
    );
  }

  late final _gst_structure_get_fractionPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<GstStructure>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Int>,
            ffi.Pointer<ffi.Int>,
          )
        >
      >('gst_structure_get_fraction');
  late final _gst_structure_get_fraction = _gst_structure_get_fractionPtr
      .asFunction<
        int Function(
          ffi.Pointer<GstStructure>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Int>,
          ffi.Pointer<ffi.Int>,
        )
      >();

  int gst_structure_get_int(
    ffi.Pointer<GstStructure> structure,
    ffi.Pointer<ffi.Char> fieldname,
    ffi.Pointer<ffi.Int> value,
  ) {
    return _gst_structure_get_int(structure, fieldname, value);
  }

  late final _gst_structure_get_intPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<GstStructure>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Int>,
          )
        >
      >('gst_structure_get_int');
  late final _gst_structure_get_int = _gst_structure_get_intPtr
      .asFunction<
        int Function(
          ffi.Pointer<GstStructure>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Int>,
        )
      >();

  ffi.Pointer<ffi.Char> gst_structure_get_name(
    ffi.Pointer<GstStructure> structure,
  ) {
    return _gst_structure_get_name(structure);
  }

  late final _gst_structure_get_namePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<GstStructure>)
        >
      >('gst_structure_get_name');
  late final _gst_structure_get_name = _gst_structure_get_namePtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<GstStructure>)>();

  void gst_util_set_object_arg(
    ffi.Pointer<GObject> object,
    ffi.Pointer<ffi.Char> name,
    ffi.Pointer<ffi.Char> value,
  ) {
    return _gst_util_set_object_arg(object, name, value);
  }

  late final _gst_util_set_object_argPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<GObject>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('gst_util_set_object_arg');
  late final _gst_util_set_object_arg = _gst_util_set_object_argPtr
      .asFunction<
        void Function(
          ffi.Pointer<GObject>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  void gst_version(
    ffi.Pointer<ffi.UnsignedInt> major,
    ffi.Pointer<ffi.UnsignedInt> minor,
    ffi.Pointer<ffi.UnsignedInt> micro,
    ffi.Pointer<ffi.UnsignedInt> nano,
  ) {
    return _gst_version(major, minor, micro, nano);
  }

  late final _gst_versionPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<ffi.UnsignedInt>,
            ffi.Pointer<ffi.UnsignedInt>,
            ffi.Pointer<ffi.UnsignedInt>,
            ffi.Pointer<ffi.UnsignedInt>,
          )
        >
      >('gst_version');
  late final _gst_version = _gst_versionPtr
      .asFunction<
        void Function(
          ffi.Pointer<ffi.UnsignedInt>,
          ffi.Pointer<ffi.UnsignedInt>,
          ffi.Pointer<ffi.UnsignedInt>,
          ffi.Pointer<ffi.UnsignedInt>,
        )
      >();

  ffi.Pointer<ffi.Char> gst_version_string() {
    return _gst_version_string();
  }

  late final _gst_version_stringPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'gst_version_string',
      );
  late final _gst_version_string = _gst_version_stringPtr
      .asFunction<ffi.Pointer<ffi.Char> Function()>();
}

final class GCond extends ffi.Struct {
  external ffi.Pointer<ffi.Void> p;

  @ffi.Array.multi([2])
  external ffi.Array<ffi.UnsignedInt> i;
}

final class GError extends ffi.Struct {
  @ffi.UnsignedInt()
  external int domain;

  @ffi.Int()
  external int code;

  external ffi.Pointer<ffi.Char> message;
}

final class GList extends ffi.Struct {
  external ffi.Pointer<ffi.Void> data;

  external ffi.Pointer<GList> next;

  external ffi.Pointer<GList> prev;
}

final class GMutex extends ffi.Union {
  external ffi.Pointer<ffi.Void> p;

  @ffi.Array.multi([2])
  external ffi.Array<ffi.UnsignedInt> i;
}

final class GObject extends ffi.Opaque {}

typedef GType = ffi.UnsignedLongLong;

/// GstAllocationParams:
/// @flags: flags to control allocation
/// @align: the desired alignment of the memory
/// @prefix: the desired prefix
/// @padding: the desired padding
///
/// Parameters to control the allocation of memory
final class GstAllocationParams extends ffi.Opaque {}

/// GstAllocator:
/// @mem_map: the implementation of the GstMemoryMapFunction
/// @mem_unmap: the implementation of the GstMemoryUnmapFunction
/// @mem_copy: the implementation of the GstMemoryCopyFunction
/// @mem_share: the implementation of the GstMemoryShareFunction
/// @mem_is_span: the implementation of the GstMemoryIsSpanFunction
/// @mem_map_full: the implementation of the GstMemoryMapFullFunction.
/// Will be used instead of @mem_map if present. (Since: 1.6)
/// @mem_unmap_full: the implementation of the GstMemoryUnmapFullFunction.
/// Will be used instead of @mem_unmap if present. (Since: 1.6)
///
/// The #GstAllocator is used to create new memory.
final class GstAllocator extends ffi.Opaque {}

final class GstAppSink extends ffi.Opaque {}

final class GstAppSrc extends ffi.Opaque {}

/// GstBin:
/// @numchildren: the number of children in this bin
/// @children: (element-type Gst.Element): the list of children in this bin
/// @children_cookie: updated whenever @children changes
/// @child_bus: internal bus for handling child messages
/// @messages: (element-type Gst.Message): queued and cached messages
/// @polling: the bin is currently calculating its state
/// @state_dirty: the bin needs to recalculate its state (deprecated)
/// @clock_dirty: the bin needs to select a new clock
/// @provided_clock: the last clock selected
/// @clock_provider: the element that provided @provided_clock
///
/// The GstBin base class. Subclasses can access these fields provided
/// the LOCK is taken.
final class GstBin extends ffi.Opaque {}

/// GstBuffer:
/// @mini_object: the parent structure
/// @pool: pointer to the pool owner of the buffer
/// @pts: presentation timestamp of the buffer, can be #GST_CLOCK_TIME_NONE when the
/// pts is not known or relevant. The pts contains the timestamp when the
/// media should be presented to the user.
/// @dts: decoding timestamp of the buffer, can be #GST_CLOCK_TIME_NONE when the
/// dts is not known or relevant. The dts contains the timestamp when the
/// media should be processed.
/// @duration: duration in time of the buffer data, can be #GST_CLOCK_TIME_NONE
/// when the duration is not known or relevant.
/// @offset: a media specific offset for the buffer data.
/// For video frames, this is the frame number of this buffer.
/// For audio samples, this is the offset of the first sample in this buffer.
/// For file data or compressed data this is the byte offset of the first
/// byte in this buffer.
/// @offset_end: the last offset contained in this buffer. It has the same
/// format as @offset.
///
/// The structure of a #GstBuffer. Use the associated macros to access the public
/// variables.
final class GstBuffer extends ffi.Struct {
  external GstMiniObject mini_object;

  external ffi.Pointer<GstBufferPool> pool;

  @GstClockTime()
  external int pts;

  @GstClockTime()
  external int dts;

  @GstClockTime()
  external int duration;

  @ffi.UnsignedLongLong()
  external int offset;

  @ffi.UnsignedLongLong()
  external int offset_end;
}

/// GstBufferPool:
/// @object: the parent structure
/// @flushing: whether the pool is currently gathering back outstanding buffers
///
/// The structure of a #GstBufferPool. Use the associated macros to access the public
/// variables.
final class GstBufferPool extends ffi.Opaque {}

/// GstBus:
/// @object: the parent structure
///
/// The opaque #GstBus data structure.
final class GstBus extends ffi.Opaque {}

/// GstCaps:
/// @mini_object: the parent type
///
/// Object describing media types.
final class GstCaps extends ffi.Opaque {}

/// GstClockTime:
///
/// A datatype to hold a time, measured in nanoseconds.
typedef GstClockTime = ffi.UnsignedLongLong;

/// GstDiscoverer:
///
/// The #GstDiscoverer structure.
final class GstDiscoverer extends ffi.Opaque {}

final class GstDiscovererInfo extends ffi.Opaque {}

/// GstDiscovererResult:
/// @GST_DISCOVERER_OK: The discovery was successful
/// @GST_DISCOVERER_URI_INVALID: the URI is invalid
/// @GST_DISCOVERER_ERROR: an error happened and the GError is set
/// @GST_DISCOVERER_TIMEOUT: the discovery timed-out
/// @GST_DISCOVERER_BUSY: the discoverer was already discovering a file
/// @GST_DISCOVERER_MISSING_PLUGINS: Some plugins are missing for full discovery
///
/// Result values for the discovery process.
sealed class GstDiscovererResult {
  static const GST_DISCOVERER_OK = 0;
  static const GST_DISCOVERER_URI_INVALID = 1;
  static const GST_DISCOVERER_ERROR = 2;
  static const GST_DISCOVERER_TIMEOUT = 3;
  static const GST_DISCOVERER_BUSY = 4;
  static const GST_DISCOVERER_MISSING_PLUGINS = 5;
}

final class GstDiscovererStreamInfo extends ffi.Opaque {}

final class GstDiscovererVideoInfo extends ffi.Opaque {}

/// GstElement:
/// @state_lock: Used to serialize execution of gst_element_set_state()
/// @state_cond: Used to signal completion of a state change
/// @state_cookie: Used to detect concurrent execution of
/// gst_element_set_state() and gst_element_get_state()
/// @target_state: the target state of an element as set by the application
/// @current_state: the current state of an element
/// @next_state: the next state of an element, can be #GST_STATE_VOID_PENDING if
/// the element is in the correct state.
/// @pending_state: the final state the element should go to, can be
/// #GST_STATE_VOID_PENDING if the element is in the correct state
/// @last_return: the last return value of an element state change
/// @bus: the bus of the element. This bus is provided to the element by the
/// parent element or the application. A #GstPipeline has a bus of its own.
/// @clock: the clock of the element. This clock is usually provided to the
/// element by the toplevel #GstPipeline.
/// @base_time: the time of the clock right before the element is set to
/// PLAYING. Subtracting @base_time from the current clock time in the PLAYING
/// state will yield the running_time against the clock.
/// @start_time: the running_time of the last PAUSED state
/// @numpads: number of pads of the element, includes both source and sink pads.
/// @pads: (element-type Gst.Pad): list of pads
/// @numsrcpads: number of source pads of the element.
/// @srcpads: (element-type Gst.Pad): list of source pads
/// @numsinkpads: number of sink pads of the element.
/// @sinkpads: (element-type Gst.Pad): list of sink pads
/// @pads_cookie: updated whenever the a pad is added or removed
/// @contexts: (element-type Gst.Context): list of contexts
///
/// GStreamer element abstract base class.
final class GstElement extends ffi.Opaque {}

final class GstElementFactory extends ffi.Opaque {}

/// GstEvent:
/// @mini_object: the parent structure
/// @type: the #GstEventType of the event
/// @timestamp: the timestamp of the event
/// @seqnum: the sequence number of the event
///
/// A #GstEvent.
final class GstEvent extends ffi.Opaque {}

/// GstFlowReturn:
/// @GST_FLOW_OK:		 Data passing was ok.
/// @GST_FLOW_NOT_LINKED:	 Pad is not linked.
/// @GST_FLOW_FLUSHING:	         Pad is flushing.
/// @GST_FLOW_EOS:                Pad is EOS.
/// @GST_FLOW_NOT_NEGOTIATED:	 Pad is not negotiated.
/// @GST_FLOW_ERROR:		 Some (fatal) error occurred. Element generating
/// this error should post an error message using
/// GST_ELEMENT_ERROR() with more details.
/// @GST_FLOW_NOT_SUPPORTED:	 This operation is not supported.
/// @GST_FLOW_CUSTOM_SUCCESS:	 Elements can use values starting from
/// this (and higher) to define custom success
/// codes.
/// @GST_FLOW_CUSTOM_SUCCESS_1:	 Pre-defined custom success code (define your
/// custom success code to this to avoid compiler
/// warnings).
/// @GST_FLOW_CUSTOM_SUCCESS_2:	 Pre-defined custom success code.
/// @GST_FLOW_CUSTOM_ERROR:	 Elements can use values starting from
/// this (and lower) to define custom error codes.
/// @GST_FLOW_CUSTOM_ERROR_1:	 Pre-defined custom error code (define your
/// custom error code to this to avoid compiler
/// warnings).
/// @GST_FLOW_CUSTOM_ERROR_2:	 Pre-defined custom error code.
///
/// The result of passing data to a pad.
///
/// Note that the custom return values should not be exposed outside of the
/// element scope.
sealed class GstFlowReturn {
  static const GST_FLOW_CUSTOM_SUCCESS_2 = 102;
  static const GST_FLOW_CUSTOM_SUCCESS_1 = 101;
  static const GST_FLOW_CUSTOM_SUCCESS = 100;
  static const GST_FLOW_OK = 0;
  static const GST_FLOW_NOT_LINKED = -1;
  static const GST_FLOW_FLUSHING = -2;
  static const GST_FLOW_EOS = -3;
  static const GST_FLOW_NOT_NEGOTIATED = -4;
  static const GST_FLOW_ERROR = -5;
  static const GST_FLOW_NOT_SUPPORTED = -6;
  static const GST_FLOW_CUSTOM_ERROR = -100;
  static const GST_FLOW_CUSTOM_ERROR_1 = -101;
  static const GST_FLOW_CUSTOM_ERROR_2 = -102;
}

/// GstFormat:
/// @GST_FORMAT_UNDEFINED: undefined format
/// @GST_FORMAT_DEFAULT: the default format of the pad/element. This can be
/// samples for raw audio, frames/fields for raw video (some, but not all,
/// elements support this; use @GST_FORMAT_TIME if you don't have a good
/// reason to query for samples/frames)
/// @GST_FORMAT_BYTES: bytes
/// @GST_FORMAT_TIME: time in nanoseconds
/// @GST_FORMAT_BUFFERS: buffers (few, if any, elements implement this as of
/// May 2009)
/// @GST_FORMAT_PERCENT: percentage of stream (few, if any, elements implement
/// this as of May 2009)
///
/// Standard predefined formats
sealed class GstFormat {
  static const GST_FORMAT_UNDEFINED = 0;
  static const GST_FORMAT_DEFAULT = 1;
  static const GST_FORMAT_BYTES = 2;
  static const GST_FORMAT_TIME = 3;
  static const GST_FORMAT_BUFFERS = 4;
  static const GST_FORMAT_PERCENT = 5;
}

/// GstMapFlags:
/// @GST_MAP_READ: map for read access
/// @GST_MAP_WRITE: map for write access
/// @GST_MAP_REF_MEMORY: Take another reference of the memory and store it in
/// the GstMapInfo. This makes sure that the memory stays valid  while it
/// is mapped and automatically unrefs it on unmap. (Since: 1.28)
/// @GST_MAP_FLAG_LAST: first flag that can be used for custom purposes
///
/// Flags used when mapping memory
sealed class GstMapFlags {
  static const GST_MAP_READ = 1;
  static const GST_MAP_WRITE = 2;

  /// GST_MAP_REF_MEMORY:
  ///
  /// Take another reference of the memory and store it in the GstMapInfo. This
  /// makes sure that the memory stays valid  while it is mapped and
  /// automatically unrefs it on unmap.
  ///
  /// Since: 1.28
  static const GST_MAP_REF_MEMORY = 256;
  static const GST_MAP_FLAG_LAST = 65536;
}

/// GstMapInfo:
/// @memory: a pointer to the mapped memory
/// @flags: flags used when mapping the memory
/// @data: (array length=size): a pointer to the mapped data
/// @size: the valid size in @data
/// @maxsize: the maximum bytes in @data
/// @user_data: extra private user_data that the implementation of the memory
/// can use to store extra info.
///
/// A structure containing the result of a map operation such as
/// gst_memory_map(). It contains the data and size.
///
/// #GstMapInfo cannot be used with g_auto() because it is ambiguous whether it
/// needs to be unmapped using gst_buffer_unmap() or gst_memory_unmap(). Instead,
/// #GstBufferMapInfo and #GstMemoryMapInfo can be used in that case.
final class GstMapInfo extends ffi.Struct {
  external ffi.Pointer<GstMemory> memory;

  @ffi.UnsignedInt()
  external int flags;

  external ffi.Pointer<ffi.UnsignedChar> data;

  @ffi.UnsignedLongLong()
  external int size;

  @ffi.UnsignedLongLong()
  external int maxsize;

  @ffi.Array.multi([4])
  external ffi.Array<ffi.Pointer<ffi.Void>> user_data;

  @ffi.Array.multi([4])
  external ffi.Array<ffi.Pointer<ffi.Void>> _gst_reserved;
}

/// GstMemory:
/// @mini_object: parent structure
/// @allocator: pointer to the #GstAllocator
/// @parent: parent memory block
/// @maxsize: the maximum size allocated
/// @align: the alignment of the memory
/// @offset: the offset where valid data starts
/// @size: the size of valid data
///
/// Base structure for memory implementations. Custom memory will put this structure
/// as the first member of their structure.
final class GstMemory extends ffi.Opaque {}

/// GstMessage:
/// @mini_object: the parent structure
/// @type: the #GstMessageType of the message
/// @timestamp: the timestamp of the message
/// @src: the src of the message
/// @seqnum: the sequence number of the message
///
/// A #GstMessage.
final class GstMessage extends ffi.Struct {
  external GstMiniObject mini_object;

  @ffi.Int()
  external int type;

  @ffi.UnsignedLongLong()
  external int timestamp;

  external ffi.Pointer<GstObject> src;

  @ffi.UnsignedInt()
  external int seqnum;

  external GMutex lock;

  external GCond cond;
}

/// GstMessageType:
/// @GST_MESSAGE_UNKNOWN: an undefined message
/// @GST_MESSAGE_EOS: end-of-stream reached in a pipeline. The application will
/// only receive this message in the PLAYING state and every time it sets a
/// pipeline to PLAYING that is in the EOS state. The application can perform a
/// flushing seek in the pipeline, which will undo the EOS state again.
/// @GST_MESSAGE_ERROR: an error occurred. When the application receives an error
/// message it should stop playback of the pipeline and not assume that more
/// data will be played. It is possible to specify a redirection url to the error
/// messages by setting a `redirect-location` field into the error message, application
/// or high level bins might use the information as required.
/// @GST_MESSAGE_WARNING: a warning occurred.
/// @GST_MESSAGE_INFO: an info message occurred
/// @GST_MESSAGE_TAG: a tag was found.
/// @GST_MESSAGE_BUFFERING: the pipeline is buffering. When the application
/// receives a buffering message in the PLAYING state for a non-live pipeline it
/// must PAUSE the pipeline until the buffering completes, when the percentage
/// field in the message is 100%. For live pipelines, no action must be
/// performed and the buffering percentage can be used to inform the user about
/// the progress.
/// @GST_MESSAGE_STATE_CHANGED: a state change happened
/// @GST_MESSAGE_STATE_DIRTY: an element changed state in a streaming thread.
/// This message is deprecated.
/// @GST_MESSAGE_STEP_DONE: a stepping operation finished.
/// @GST_MESSAGE_CLOCK_PROVIDE: an element notifies its capability of providing
/// a clock. This message is used internally and
/// never forwarded to the application.
/// @GST_MESSAGE_CLOCK_LOST: The current clock as selected by the pipeline became
/// unusable. The pipeline will select a new clock on
/// the next PLAYING state change. The application
/// should set the pipeline to PAUSED and back to
/// PLAYING when this message is received.
/// @GST_MESSAGE_NEW_CLOCK: a new clock was selected in the pipeline.
/// @GST_MESSAGE_STRUCTURE_CHANGE: the structure of the pipeline changed. This
/// message is used internally and never forwarded to the application.
/// @GST_MESSAGE_STREAM_STATUS: status about a stream, emitted when it starts,
/// stops, errors, etc..
/// @GST_MESSAGE_APPLICATION: message posted by the application, possibly
/// via an application-specific element.
/// @GST_MESSAGE_ELEMENT: element-specific message, see the specific element's
/// documentation
/// @GST_MESSAGE_SEGMENT_START: pipeline started playback of a segment. This
/// message is used internally and never forwarded to the application.
/// @GST_MESSAGE_SEGMENT_DONE: pipeline completed playback of a segment. This
/// message is forwarded to the application after all elements that posted
/// @GST_MESSAGE_SEGMENT_START posted a GST_MESSAGE_SEGMENT_DONE message.
/// @GST_MESSAGE_DURATION_CHANGED: The duration of a pipeline changed. The
/// application can get the new duration with a duration query.
/// @GST_MESSAGE_ASYNC_START: Posted by elements when they start an ASYNC
/// #GstStateChange. This message is not forwarded to the application but is used
/// internally.
/// @GST_MESSAGE_ASYNC_DONE: Posted by elements when they complete an ASYNC
/// #GstStateChange. The application will only receive this message from the toplevel
/// pipeline.
/// @GST_MESSAGE_LATENCY: Posted by elements when their latency changes. The
/// application should recalculate and distribute a new latency.
/// @GST_MESSAGE_REQUEST_STATE: Posted by elements when they want the pipeline to
/// change state. This message is a suggestion to the application which can
/// decide to perform the state change on (part of) the pipeline.
/// @GST_MESSAGE_STEP_START: A stepping operation was started.
/// @GST_MESSAGE_QOS: A buffer was dropped or an element changed its processing
/// strategy for Quality of Service reasons.
/// @GST_MESSAGE_PROGRESS: A progress message.
/// @GST_MESSAGE_TOC: A new table of contents (TOC) was found or previously found TOC
/// was updated.
/// @GST_MESSAGE_RESET_TIME: Message to request resetting the pipeline's
/// running time from the pipeline. This is an internal message which
/// applications will likely never receive.
/// @GST_MESSAGE_STREAM_START: Message indicating start of a new stream. Useful
/// e.g. when using playbin in gapless playback mode, to get notified when
/// the next title actually starts playing (which will be some time after
/// the URI for the next title has been set).
/// @GST_MESSAGE_NEED_CONTEXT: Message indicating that an element wants a specific context (Since: 1.2)
/// @GST_MESSAGE_HAVE_CONTEXT: Message indicating that an element created a context (Since: 1.2)
/// @GST_MESSAGE_EXTENDED: Message is an extended message type (see below).
/// These extended message IDs can't be used directly with mask-based API
/// like gst_bus_poll() or gst_bus_timed_pop_filtered(), but you can still
/// filter for GST_MESSAGE_EXTENDED and then check the result for the
/// specific type. (Since: 1.4)
/// @GST_MESSAGE_DEVICE_ADDED: Message indicating a #GstDevice was added to
/// a #GstDeviceProvider (Since: 1.4)
/// @GST_MESSAGE_DEVICE_REMOVED: Message indicating a #GstDevice was removed
/// from a #GstDeviceProvider (Since: 1.4)
/// @GST_MESSAGE_PROPERTY_NOTIFY: Message indicating a #GObject property has
/// changed (Since: 1.10)
/// @GST_MESSAGE_STREAM_COLLECTION: Message indicating a new #GstStreamCollection
/// is available (Since: 1.10)
/// @GST_MESSAGE_STREAMS_SELECTED: Message indicating the active selection of
/// #GstStreams has changed (Since: 1.10)
/// @GST_MESSAGE_REDIRECT: Message indicating to request the application to
/// try to play the given URL(s). Useful if for example a HTTP 302/303
/// response is received with a non-HTTP URL inside. (Since: 1.10)
/// @GST_MESSAGE_DEVICE_CHANGED: Message indicating a #GstDevice was changed
/// a #GstDeviceProvider (Since: 1.16)
/// @GST_MESSAGE_INSTANT_RATE_REQUEST: Message sent by elements to request the
/// running time from the pipeline when an instant rate change should
/// be applied (which may be in the past when the answer arrives). (Since: 1.18)
/// @GST_MESSAGE_DEVICE_MONITOR_STARTED: Message indicating the
/// #GstDeviceMonitor has completed async startup (Since: 1.28)
/// @GST_MESSAGE_ANY: mask for all of the above messages.
///
/// The different message types that are available.
sealed class GstMessageType {
  static const GST_MESSAGE_UNKNOWN = 0;
  static const GST_MESSAGE_EOS = 1;
  static const GST_MESSAGE_ERROR = 2;
  static const GST_MESSAGE_WARNING = 4;
  static const GST_MESSAGE_INFO = 8;
  static const GST_MESSAGE_TAG = 16;
  static const GST_MESSAGE_BUFFERING = 32;
  static const GST_MESSAGE_STATE_CHANGED = 64;
  static const GST_MESSAGE_STATE_DIRTY = 128;
  static const GST_MESSAGE_STEP_DONE = 256;
  static const GST_MESSAGE_CLOCK_PROVIDE = 512;
  static const GST_MESSAGE_CLOCK_LOST = 1024;
  static const GST_MESSAGE_NEW_CLOCK = 2048;
  static const GST_MESSAGE_STRUCTURE_CHANGE = 4096;
  static const GST_MESSAGE_STREAM_STATUS = 8192;
  static const GST_MESSAGE_APPLICATION = 16384;
  static const GST_MESSAGE_ELEMENT = 32768;
  static const GST_MESSAGE_SEGMENT_START = 65536;
  static const GST_MESSAGE_SEGMENT_DONE = 131072;
  static const GST_MESSAGE_DURATION_CHANGED = 262144;
  static const GST_MESSAGE_LATENCY = 524288;
  static const GST_MESSAGE_ASYNC_START = 1048576;
  static const GST_MESSAGE_ASYNC_DONE = 2097152;
  static const GST_MESSAGE_REQUEST_STATE = 4194304;
  static const GST_MESSAGE_STEP_START = 8388608;
  static const GST_MESSAGE_QOS = 16777216;
  static const GST_MESSAGE_PROGRESS = 33554432;
  static const GST_MESSAGE_TOC = 67108864;
  static const GST_MESSAGE_RESET_TIME = 134217728;
  static const GST_MESSAGE_STREAM_START = 268435456;
  static const GST_MESSAGE_NEED_CONTEXT = 536870912;
  static const GST_MESSAGE_HAVE_CONTEXT = 1073741824;
  static const GST_MESSAGE_EXTENDED = -2147483648;
  static const GST_MESSAGE_DEVICE_ADDED = -2147483647;
  static const GST_MESSAGE_DEVICE_REMOVED = -2147483646;
  static const GST_MESSAGE_PROPERTY_NOTIFY = -2147483645;
  static const GST_MESSAGE_STREAM_COLLECTION = -2147483644;
  static const GST_MESSAGE_STREAMS_SELECTED = -2147483643;
  static const GST_MESSAGE_REDIRECT = -2147483642;
  static const GST_MESSAGE_DEVICE_CHANGED = -2147483641;
  static const GST_MESSAGE_INSTANT_RATE_REQUEST = -2147483640;

  /// GST_MESSAGE_DEVICE_MONITOR_STARTED:
  ///
  /// Message indicating the #GstDeviceMonitor has completed async startup.
  ///
  /// Since: 1.28
  static const GST_MESSAGE_DEVICE_MONITOR_STARTED = -2147483639;
  static const GST_MESSAGE_ANY = -1;
}

/// GstMiniObject: (ref-func gst_mini_object_ref) (unref-func gst_mini_object_unref) (set-value-func g_value_set_boxed) (get-value-func g_value_get_boxed)
/// @type: the GType of the object
/// @refcount: atomic refcount
/// @lockstate: atomic state of the locks
/// @flags: extra flags.
/// @copy: a copy function
/// @dispose: a dispose function
/// @free: the free function
///
/// Base class for refcounted lightweight objects.
final class GstMiniObject extends ffi.Struct {
  @GType()
  external int type;

  @ffi.Int()
  external int refcount;

  @ffi.Int()
  external int lockstate;

  @ffi.UnsignedInt()
  external int flags;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<GstMiniObject> Function(ffi.Pointer<GstMiniObject> obj)
    >
  >
  copy;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Int Function(ffi.Pointer<GstMiniObject> obj)>
  >
  dispose;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GstMiniObject> obj)>
  >
  free;

  @ffi.UnsignedInt()
  external int priv_uint;

  external ffi.Pointer<ffi.Void> priv_pointer;
}

/// GstObject:
/// @lock: object LOCK
/// @name: The name of the object
/// @parent: this object's parent, weak ref
/// @flags: flags for this object
///
/// GStreamer base object class.
final class GstObject extends ffi.Opaque {}

/// GstPad:
/// @element_private: private data owned by the parent element
/// @padtemplate: padtemplate for this pad
/// @direction: the direction of the pad, cannot change after creating
/// the pad.
///
/// The #GstPad structure. Use the functions to update the variables.
final class GstPad extends ffi.Opaque {}

final class GstPlugin extends ffi.Opaque {}

/// GstRegistry:
///
/// Opaque #GstRegistry structure.
final class GstRegistry extends ffi.Opaque {}

final class GstSample extends ffi.Opaque {}

/// GstState:
/// @GST_STATE_VOID_PENDING: no pending state.
/// @GST_STATE_NULL        : the NULL state or initial state of an element.
/// @GST_STATE_READY       : the element is ready to go to PAUSED.
/// @GST_STATE_PAUSED      : the element is PAUSED, it is ready to accept and
/// process data. Sink elements however only accept one
/// buffer and then block.
/// @GST_STATE_PLAYING     : the element is PLAYING, the #GstClock is running and
/// the data is flowing.
///
/// The possible states an element can be in. States can be changed using
/// gst_element_set_state() and checked using gst_element_get_state().
sealed class GstState {
  static const GST_STATE_VOID_PENDING = 0;
  static const GST_STATE_NULL = 1;
  static const GST_STATE_READY = 2;
  static const GST_STATE_PAUSED = 3;
  static const GST_STATE_PLAYING = 4;
}

/// GstStateChangeReturn:
/// @GST_STATE_CHANGE_FAILURE   : the state change failed
/// @GST_STATE_CHANGE_SUCCESS   : the state change succeeded
/// @GST_STATE_CHANGE_ASYNC     : the state change will happen asynchronously
/// @GST_STATE_CHANGE_NO_PREROLL: the state change succeeded but the element
/// cannot produce data in %GST_STATE_PAUSED.
/// This typically happens with live sources.
///
/// The possible return values from a state change function such as
/// gst_element_set_state(). Only @GST_STATE_CHANGE_FAILURE is a real failure.
sealed class GstStateChangeReturn {
  static const GST_STATE_CHANGE_FAILURE = 0;
  static const GST_STATE_CHANGE_SUCCESS = 1;
  static const GST_STATE_CHANGE_ASYNC = 2;
  static const GST_STATE_CHANGE_NO_PREROLL = 3;
}

/// GstStructure:
/// @type: the GType of a structure
///
/// The GstStructure object. Most fields are private.
final class GstStructure extends ffi.Opaque {}
